version: "3.0"

services:
  # FastAPI
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app